blog/urls.py
#!/usr/bin/python3
# Time : 2019/11/14 13:07 
# Author : zcl
from . import views
from django.conf.urls import url


app_name='blog'
urlpatterns = [
    url(r'^index/$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    # url(r'^search/$', views.search, name='search'),
    url(r'^publish/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
]

blogproject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include
from blog.feeds import AllPostsRssFeed
from . import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'^comments', include('comments.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),   
    url(r'^search/', include('haystack.urls')),  #搜索的视图函数和 URL 模式 django haystack 都已经帮我们写好了，只需要项目的 urls.py 中包含它：
    url(r'^about/',views.about,name='about'),
    url(r'^contact/',views.contact,name='contact'),
]

login/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include
from login import views

app_name='login'
urlpatterns = [
    # path('index/', views.index,name="index"),
    url('login/', views.login,name="login"),
    url('register/', views.register,name="register"),
    url('logout/', views.logout,name="logout"),
    url('confirm/', views.user_confirm,name="confirm"),
    url('captcha/', include('captcha.urls'),name="captcha"),
]

login/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class Userprofile(AbstractUser):	#AbstractUser自带username、password、email、first_name、last_name
    gender = (
        ('male', '男'),
        ('female', '女')
    )
    sex = models.CharField(max_length=32, choices=gender, default='男')
    c_time = models.DateField(auto_now_add=True)
    has_confirmed = models.BooleanField(default=False)
    birthday = models.DateField("出生年月",null=True, blank=True)
    mobile = models.CharField("电话", max_length=11,default=12356)
    def __str__(self):
        return self.username

    class Meta:
        ordering = ['-c_time']
        verbose_name = '用户'
        verbose_name_plural = '用户'


class ConfirmString(models.Model):
    code = models.CharField(max_length=256)
    user = models.OneToOneField('Userprofile', on_delete=models.CASCADE)
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.name + self.code

    class Meta:
        ordering = ['-c_time']
        verbose_name = '确认码'
        verbose_name_plural = '确认码'

login/forms.py
from django import forms
from captcha.fields import CaptchaField


class UserForm(forms.Form):
    username = forms.CharField(label='用户名/电话/邮箱', max_length=128, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                                          'placeholder': 'username',
                                                                                          'autofocus': ''}))
    password = forms.CharField(label='密码', max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                                          'placeholder': 'password'}))
    # captcha = CaptchaField(label='验证码')  #验证码


class RegisterForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="确认密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    mobile = forms.CharField(label="电话", max_length=11,widget=forms.TextInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='性别', choices=gender)
    captcha = CaptchaField(label='验证码')

login/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.conf import settings
from . import models
from . models import Userprofile
from . import forms
import hashlib
import datetime
from django.contrib.auth import authenticate
from django.contrib.auth import login as auto_login
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# Create your views here.


def hash_code(s, salt='mysite'):
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())
    return h.hexdigest()


def make_confirm_string(user):   #生成的验证码以用户名+时间戳 生成的hash代码，后面网邮件里发的链接，携带hash代码，发到指定验证的url验证
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    code = hash_code(user.username, now)
    models.ConfirmString.objects.create(code=code, user=user)
    return code


def send_email(email, code):

    from django.core.mail import EmailMultiAlternatives

    subject = '来自"中华大西瓜"的注册确认邮件'

    text_content = '''
                    如果你看到这条消息，说明你的邮箱服务器不提供HTML链接功能，请联系管理员！'''

    html_content = '''
                    <p>感谢注册<a href="http://{}/confirm/?code={}" target=blank>www.liujiangblog.com</a>，\
                    这里是刘江的博客和教程站点，专注于Python、Django和机器学习技术的分享！</p>
                    <p>请点击站点链接完成注册确认！</p>
                    <p>此链接有效期为{}天！</p>
                    '''.format('www.daxigua.asia:82', code, settings.CONFIRM_DAYS)

    msg = EmailMultiAlternatives(subject, text_content, settings.EMAIL_HOST_USER, [email])
    msg.attach_alternative(html_content, "text/html")
    msg.send()


@login_required
def index(request):
    # if not request.session.get('is_login', None):
    # if request.COOKIES.get("is_login",None):
        # return redirect('/login/')
    return render(request, 'login/index.html')
    # return redirect ("/")


def login(request):
    # if not request.session.get('is_login', None):  # 代码后面设置了，如果登陆成功，session里会加入is_login，不允许重复登录
    # if request.COOKIES.get("is_login",None):
    #     return redirect('/')
    ssession_look = request.session.flush()
    cookie_look = request.COOKIES
    print("ssession_look",ssession_look)
    print("cookie_look",cookie_look)
    if request.method == 'POST':
        login_form = forms.UserForm(request.POST)   #把request.POST转成form表单类
        message = '请检查填写的内容！'  
        if login_form.is_valid():  #cleaned_data  {'password': '1245', 'username': 'QQQ', 'captcha': ['90392e2c93228b7fc4cafc438df139659a715991', '']}
            username = login_form.cleaned_data.get('username')   #cleaned_data: html中input标签里输入的内容，字典类型,input标签中，name=username
            password = login_form.cleaned_data.get('password')
            # try:
            #     user = models.Userprofile.objects.get(Q(username=username) | Q(mobile=username))   #将表单验证过的数据拿出来，创建models
            # except :
            #     message = '用户不存在！'    #通过locals() 传入模板中的{{ message }}
            #     return render(request, 'login/login.html', locals())

            # if not Userprofile.has_confirmed:   #判断user的has_confirmed字段
            #     message = '该用户还未经过邮件确认！'
            #     return render(request, 'login/login.html', locals())
            user = authenticate(username=username, password=password)
            if user:
            # if Userprofile.password == hash_code(password) or user.password == password:  #用户、有限认证、密码都通过后，设置session里字典内容
                auto_login(request, user)
                request.session['is_login'] = True
                request.session['user_id'] = user.id
                request.session['user_name'] = user.username
                print("auth/////////////")
                # reverse('reverse:userInfo',kwargs={'user_id':10})
                url = reverse("blog:index")
                print(url)
                response = redirect(url)
                # response.set_signed_cookie("is_login",True,salt="blog")
                # response.set_signed_cookie("user_id",user.id,salt="blog")
                # response.set_signed_cookie("user_name",user.username,salt="blog")
                return response
            else:
                message = '密码不正确！'  
                return render(request, 'login/login.html', locals())
        else:
            return render(request, 'login/login.html', locals())

    login_form = forms.UserForm()   #清空login_form变量 内容
    return render(request, 'login/login.html', locals())   #locals会把本地变量，此处有message、login_form、username、password变量传入模板中


def register(request):
    # if not request.session.get('is_login', None):
    if request.COOKIES.get("is_login",None):
        return redirect('/index/')

    if request.method == 'POST':
        register_form = forms.RegisterForm(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():
            username = register_form.cleaned_data.get('username')
            password1 = register_form.cleaned_data.get('password1')
            password2 = register_form.cleaned_data.get('password2')
            email = register_form.cleaned_data.get('email')
            mobile = register_form.cleaned_data.get('mobile')
            sex = register_form.cleaned_data.get('sex')

            if password1 != password2:
                message = '两次输入的密码不同！'
                return render(request, 'login/register.html', locals())
            else:
                same_name_user = models.Userprofile.objects.filter(username=username)
                if same_name_user:
                    message = '用户名已经存在'
                    return render(request, 'login/register.html', locals())
                same_email_user = models.Userprofile.objects.filter(email=email)
                if same_email_user:
                    message = '该邮箱已经被注册了！'
                    return render(request, 'login/register.html', locals())
                same_mobile_user = models.Userprofile.objects.filter(mobile=mobile)
                if same_mobile_user:
                    message = '该手机号已经被注册了！'
                    return render(request, 'login/register.html', locals())

                new_user = models.Userprofile()
                new_user.username = username
                new_user.password = hash_code(password1)
                new_user.email = email
                new_user.mobile = mobile
                new_user.sex = sex
                new_user.save()

                code = make_confirm_string(new_user)
                send_email(email, code)

                message = '请前往邮箱进行确认！'
                return render(request, 'login/confirm.html', locals())
        else:
            return render(request, 'login/register.html', locals())
    register_form = forms.RegisterForm()
    return render(request, 'login/register.html', locals())


def logout(request):
    # if not request.session.get('is_login', None):
    #     return redirect('/login/')

    request.session.flush()  #登陆退出，消除session
    # del request.session['is_login']
    print('logout...........')
    return redirect("/login/login")


def user_confirm(request):
    code = request.GET.get('code', None)
    message = ''

    try:
        confirm = models.ConfirmString.objects.get(code=code)
    except:
        message = '无效的确认请求！'
        return render(request, 'login/confirm.html', locals())

    c_time = confirm.c_time
    now = datetime.datetime.now()
    if now > c_time + datetime.timedelta(settings.CONFIRM_DAYS):
        confirm.user.delete()
        message = '您的邮件已经过期！请重新注册！'
        return render(request, 'login/confirm.html', locals())
    else:
        confirm.user.has_confirmed = True     #联表查询
        confirm.user.save() #把user保存
        confirm.delete()   #把验证实例删掉
        message = '感谢确认，请使用账户登录！'
        return render(request, 'login/confirm.html', locals())

templates/ToDel/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>我的博客</title>
    <style>
        span.highlighted {
            color: red;
        }
    </style>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
{#    <link rel="stylesheet" href="css/bootstrap.min.css">#}
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
{#    <link rel="stylesheet" href="css/pace.css">#}
{#    <link rel="stylesheet" href="css/custom.css">#}
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">


    <!-- js -->
{#    <script src="js/jquery-2.1.3.min.js"></script>#}
{#    <script src="js/bootstrap.min.js"></script>#}
{#    <script src="js/pace.min.js"></script>#}
{#    <script src="js/modernizr.custom.js"></script>#}
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
{#                    <h1><a href="index.html"><b>我的</b>博客</a></h1>#}
                    <h1><a href="{% url 'blog:index' %}"><b>我的</b>博客</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li role="presentation" class="active"><a href="index.html" data-hover="首页">首页</a></li>
                            <li role="presentation" class="active"><a href="about.html" data-hover="关于">关于</a></li>
                            <li role="presentation" class="active"><a href="contact.html" data-hover="联系">联系</a></li>
                            <li role="presentation" class="active"><a href="#" data-hover="登陆">登陆</a></li>
                        </ul>
                    </div>
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                          <input type="search" name="q" placeholder="搜索" required>
                          <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
        <main class="col-md-8">
            {% block main %}
            {% endblock main %}
        </main>
        <aside class="col-md-4">
          {% block toc %}
          {% endblock toc %}
                <div class="widget widget-recent-posts">
                            <h3 class="widget-title">最新文章</h3>
{#                            {% get_recent_posts as recent_post_list %} get_recent_posts 是自定义的模板标签，最上面要加模板文件加载进来{% load blog_tags %}   #}
                            {% get_recent_posts as recent_post_list %}
                                  <ul>
                                    {% for post in recent_post_list %}
                                    <li>
                                      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                    </li>
                                    {% empty %}
                                    暂无文章！
                                    {% endfor %}
                                  </ul>
                        </div>
                        <div class="widget widget-archives">
                            <h3 class="widget-title">归档</h3>
                            {% archives as date_list %}
                              <ul>
                                {% for date in date_list %}
                                <li>
                                  <a href="{% url 'blog:archives' date.year date.month %}">
                                    {{ date.year }} 年 {{ date.month }} 月
                                  </a>
                                </li>
                                {% endfor %}
                              </ul>
                        </div>

                        <div class="widget widget-category">
                            <h3 class="widget-title">分类</h3>
                            {% get_categories as category_list %}
                                <ul>
                                  {% for category in category_list %}
                                  <li>
                                    <a href="{% url 'blog:category' category.pk %}">{{ category.name }}
                                      <span class="post-count">({{ category.num_posts }})</span>
                                    </a>
                                  </li>
                                  {% empty %}
                                  暂无分类！
                                  {% endfor %}
                                </ul>
                        </div>

                        <ul>
                      {% for category in category_list %}
                      <li>
                        <a href="{% url 'blog:category' category.pk %}">{{ category.name }}
                          <span class="post-count">({{ category.num_posts }})</span>
                        </a>
                      </li>
                      {% empty %}
                      暂无分类！
                      {% endfor %}
                    </ul>

                        <div class="widget widget-tag-cloud">
                            <h3 class="widget-title">标签云</h3>
                            {% get_tags as tag_list %}
                            <ul>
                                {% for tag in tag_list %}
                                <li>
                                <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                                <!-- <a href="#">{{ tag.name }}</a> -->
                                </li>
                                {% empty %}
                                暂无标签！
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="rss">
                            <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                        </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

{#<script src="js/script.js"></script>#}
<script src="{% static 'blog/js/script.js' %}"></script>
</body>
</html>

templates/ToDel/login.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>love</title>
    <link href="favicon.ico" rel="shortcut icon" />
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.4.0/css/bootstrap.min.css" rel="stylesheet">
</head>

<!-- <link rel="stylesheet" href="{% static '/login/QQphoto.jpg' %}"> -->

<body style=" background: url('{% static "blog/img/login.jpg" %}') no-repeat center center fixed; background-size: 100%;">

    <div class="modal-dialog" style="margin-top: 10%;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-center" id="myModalLabel">登录</h4>
            </div>
            <div class="modal-body" id = "model-body">
                <div class="form-group">
                    <input type="text" class="form-control"placeholder="用户名" autocomplete="off">
                </div>
                <div class="form-group">
 
                    <input type="password" class="form-control" placeholder="密码" autocomplete="off">
                </div>
            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <button type="button" class="btn btn-primary form-control">登录</button>
                </div>
                <div class="form-group">
                    <button type="button" class="btn btn-default form-control">注册</button>
                </div>
 
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
 
</body>
</html>